language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-22.0.1
    - android-19
before_install:
  - rm pom.xml
script:
  - ./setup_env.sh ant
  - ant clean
  - ant debug

