name: "Detect wrong settings"

on:
    pull_request:
        branches: [ master, stable-* ]

# Declare default permissions as read only.
permissions: read-all

concurrency:
    group: detect-wrong-settings-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    detectWrongSettings:
        runs-on: ubuntu-22.04

        steps:
            -   uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
            -   name: Set up JDK 17
                uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8 # v4
                with:
                    distribution: "temurin"
                    java-version: 17
            -   name: Detect SNAPSHOT
                run: scripts/analysis/detectWrongSettings.sh
