# SPDX-FileCopyrightText: 2023-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-FileCopyrightText: 2023 Tobias Kaminsky <tobias@kaminsky.me>
# SPDX-License-Identifier: AGPL-3.0-or-later OR GPL-2.0-only

name: "Detect wrong settings"

on:
    pull_request:
        branches: [ master, stable-* ]

# Declare default permissions as read only.
permissions: read-all

concurrency:
    group: detect-wrong-settings-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    detectWrongSettings:
        runs-on: ubuntu-24.04

        steps:
            -   uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            -   name: Set up JDK 17
                uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
                with:
                    distribution: "temurin"
                    java-version: 17
            -   name: Detect SNAPSHOT
                run: scripts/analysis/detectWrongSettings.sh
