name: "Detect wrong settings"

on:
    pull_request:
        branches: [ master, stable-* ]

# Declare default permissions as read only.
permissions: read-all

concurrency:
    group: detect-wrong-settings-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    detectWrongSettings:
        runs-on: ubuntu-22.04

        steps:
            -   uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
            -   name: Set up JDK 17
                uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3
                with:
                    distribution: "temurin"
                    java-version: 17
            -   name: Detect SNAPSHOT
                run: scripts/analysis/detectWrongSettings.sh
