# synced from @nextcloud/android-config

# SPDX-FileCopyrightText: 2022-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-FileCopyrightText: 2023 Andy Scherzinger <info@andy-scherzinger.de>
# SPDX-FileCopyrightText: 2022 Tobias Kaminsky <tobias@kaminsky.me>
# SPDX-FileCopyrightText: 2022 √Ålvaro Brey <alvaro@alvarobrey.com>
# SPDX-License-Identifier: GPL-3.0-or-later

name: "Detect new java files"

on:
  pull_request:
    branches: [ master, main, stable-* ]

permissions: read-all

concurrency:
  group: detect-new-java-files-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  detectNewJavaFiles:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b # v1.2.4
        with:
          output: ','
      - name: Detect new java files
        run: |
          if [ -z '${{ steps.file_changes.outputs.files_added }}' ]; then
              echo "No new files added"
              exit 0
          fi
          new_java=$(echo '${{ steps.file_changes.outputs.files_added }}' | tr ',' '\n' | grep '\.java$' | cat)
          if [ -n "$new_java" ]; then
              # shellcheck disable=SC2016
              printf 'New java files detected:\n```\n%s\n```\n' "$new_java" | tee "$GITHUB_STEP_SUMMARY"
              exit 1
          else
              echo "No new java files detected"
              exit 0
          fi
