# SPDX-FileCopyrightText: 2023-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-FileCopyrightText: 2023 Tobias Kaminsky <tobias@kaminsky.me>
# SPDX-License-Identifier: AGPL-3.0-or-later OR GPL-2.0-only

name: "Detect wrong settings"

on:
    pull_request:
        branches: [ master, stable-* ]

# Declare default permissions as read only.
permissions: read-all

concurrency:
    group: detect-wrong-settings-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    detectWrongSettings:
        runs-on: ubuntu-24.04

        steps:
            -   uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
            -   name: Set up JDK 17
                uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
                with:
                    distribution: "temurin"
                    java-version: 17
            -   name: Detect SNAPSHOT
                run: scripts/analysis/detectWrongSettings.sh
