---
name: 'Close stale issues'
on:
  schedule:
    - cron: '0 0 * * *'

# Declare default permissions as read only.
permissions: read-all

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@5ebf00ea0e4c1561e9b43a292ed34424fb1d4578 # v6
        with:
          days-before-stale: 28
          days-before-close: 14
          days-before-pr-close: -1
          only-labels: 'bug,needs info'
          exempt-issue-labels: 'no-stale'
          stale-issue-message: >-
            This bug report did not receive an update in the last 4 weeks.
            Please take a look again and update the issue with new details,
            otherwise the issue will be automatically closed in 2 weeks. Thank you!
          exempt-all-pr-milestones: true
