# synced from @nextcloud/android-config

# SPDX-FileCopyrightText: 2023-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-FileCopyrightText: 2023 Tobias Kaminsky <tobias@kaminsky.me>
# SPDX-FileCopyrightText: 2022 √Ålvaro Brey <alvaro@alvarobrey.com>
# SPDX-License-Identifier: GPL-3.0-or-later

name: 'Close stale issues'
on:
  schedule:
    - cron: '0 0 * * *'

# Declare default permissions as read only.
permissions: read-all

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@997185467fa4f803885201cee163a9f38240193d # v10.1.1
        with:
          days-before-stale: 28
          days-before-close: 14
          days-before-pr-close: -1
          only-labels: 'bug,needs info'
          exempt-issue-labels: 'no-stale'
          stale-issue-message: >-
            This bug report did not receive an update in the last 4 weeks.
            Please take a look again and update the issue with new details,
            otherwise the issue will be automatically closed in 2 weeks. Thank you!
          exempt-all-pr-milestones: true
          labels-to-remove-when-unstale: 'needs info'
